language: python
sudo: false

git:
  submodules: false

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi

install:
  - pip$PYTHON_VERSION install --upgrade -e.[test]

script:
  - python$PYTHON_VERSION setup.py test
